
version: '3.4'

services:

  apache:
    build: src/docker/apache
    container_name: apache-degrade
    depends_on: 
     - express
    ports:
     - "7653:80"
    networks: 
     - net1

  nginx:
    build: src/docker/nginx
    container_name: kil-ssi-nginx
    depends_on: 
     - express
    ports:
     - "7654:80"
    networks: 
     - net1
    volumes:
     - type: bind
       source: ./src/docker/nginx/html/
       target: /usr/share/nginx/html
     - type: bind
       source: ./src/docker/nginx/conf.d/
       target: /etc/nginx/conf.d/

  express:
    build: src/docker/express
    container_name: kil-express
    ports:
     - "7655:8080"
    networks: 
     - net1
          
networks:
  net1:
    
#volumes:
#  - html:
  
  
  