
FROM httpd

COPY html/ /usr/local/apache2/htdocs/
#COPY apache_kil.conf /usr/local/apache2/conf/extra/
COPY httpd.conf /usr/local/apache2/conf/
#FROM ubuntu
#RUN apt-get update
#RUN apt-get -y install apache2

#CMD 
